---
#
# Ansible managed
#
repository:
  description: Install and configure spamassassin on your system.
  homepage: https://buluma.github.io/
  topics: spamassassin, installer, package, ansible, molecule, playbook
